[build]
builder = "nixpacks"
buildCommand = "cp .env.example .env && composer install --optimize-autoloader --no-dev && php artisan key:generate --force"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
